# ansible-playbook .ansible/deploy.yaml -i .ansible/inventories/production/hosts --vault-id ~/.tokens/vault.txt

- hosts: tools
  roles:
    - common

  tasks:

    - include_role:
        name: docker
        tasks_from: stack_deploy
